apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: pc-api-{NAMESPACE}-{TENANT_NAME}
spec:
  selector:
    matchLabels:
      app: pc-api-{NAMESPACE}-{TENANT_NAME}
  replicas: 4
  template:
    metadata:
      labels:
        app: pc-api-{NAMESPACE}-{TENANT_NAME}
    spec:
      containers:
        - name: pc-api
          image: 9870050478/linux_tweet_app:{RELEASE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
