apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pc-api-{NAMESPACE}-{TENANT_NAME}
  name: pc-api-svc-{NAMESPACE}-{TENANT_NAME}
  namespace: dev
spec:
  ports:
    - name: pc-api-svc-{NAMESPACE}-{TENANT_NAME}
      port: 80
      targetPort: 80
  selector:
    app: pc-api-{NAMESPACE}-{TENANT_NAME}
status:
  loadBalancer: {}
